<a href="https://colab.research.google.com/github/bennarthurdev/python/blob/main/benn_amaral_ex03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução à Ciência de Dados - UFPB
Professor: Yuri Malheiros

## NumPy

Implemente a função `distance` abaixo. Ela deve receber dois pontos e retornar a distância euclidiana entre eles. Cada ponto é representado por um array do NumPy, por exemplo, `p1 = np.array([2,4])` representa o ponto com coordenadas `x=2` e `y=4`.

In [12]:
import numpy as np
from math import sqrt
def distance(p1, p2):
    """
    >>> distance(np.array([0,0]), np.array([1,1]))
    1.4142135623730951
    
    >>> distance(np.array([1,2]), np.array([3,4]))
    2.8284271247461903
    
    >>> distance(np.array([5,2]), np.array([-2,-1]))
    7.615773105863909
    """
    d = ((p1[0] - p2[0])**2) + ((p1[1] - p2[1])**2)
    sqrt_d = sqrt(d)
    return sqrt_d 

    # ADICIONE O SEU CÓDIGO AQUI

<class 'numpy.ndarray'>
float64
[[2 4]]


Implemente a função `n_distances` abaixo. Ela recebe um ponto (`p1`), como um array do NumPy, e uma lista de pontos (`points`), uma matriz do NumPy, onde cada linha representa um ponto.

Esta função deve retornar a distância de `p1` para todos os pontos da matriz `points`. O retorno também é uma matriz, onde cada linha tem a distância de `p1` para o ponto daquela linha.

In [44]:
import math
def n_distances(p1, points):
    """
    >>> n_distances(np.array([0,0]), np.array([[1,1]]))
    array([1.41421356])
    
    >>> n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
    array([1.41421356, 2.82842712])
    
    >>> n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
    """
    x = p1[0] - points[: , 0]
    y = p1[1] - points[: , 1]
    d_euclidian = (x**2 + y**2)**(1/2)
    return d_euclidian

    

array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])

## Teste

In [45]:
import doctest

doctest.testmod(verbose=True)

Trying:
    distance(np.array([0,0]), np.array([1,1]))
Expecting:
    1.4142135623730951
ok
Trying:
    distance(np.array([1,2]), np.array([3,4]))
Expecting:
    2.8284271247461903
ok
Trying:
    distance(np.array([5,2]), np.array([-2,-1]))
Expecting:
    7.615773105863909
ok
Trying:
    n_distances(np.array([0,0]), np.array([[1,1]]))
Expecting:
    array([1.41421356])
ok
Trying:
    n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
Expecting:
    array([1.41421356, 2.82842712])
ok
Trying:
    n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
Expecting:
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
ok
1 items had no tests:
    __main__
2 items passed all tests:
   3 tests in __main__.distance
   3 tests in __main__.n_distances
6 tests in 3 items.
6 passed and 0 failed.
Test passed.


TestResults(failed=0, attempted=6)

# Nova seção

## Estudo

### Intro

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3] , [4,5,6]]) #create a numpy.ndarray object
type(arr)

numpy.ndarray

In [ ]:
arr.shape ##Returns a tuple that shows the number of elements along each

(2, 3)

In [ ]:
arr.dtype ## In numpy all the data has to be of the same type and integers and floats are represented by 64-bits

dtype('int64')

## Aritmetics

In [ ]:
arr_2 = np.array([[5,6,7] , [8,9,10]])
# Sum between two ndarrays
arr + arr_2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
arr * arr_2

array([[ 5, 12, 21],
       [32, 45, 60]])

In [ ]:
result = arr / arr_2
np.around(result , 4) # ndarray object, number of decimal values,  

array([[0.2   , 0.3333, 0.4286],
       [0.5   , 0.5556, 0.6   ]])

In [ ]:
arr ** arr_2

array([[       1,       64,     2187],
       [   65536,  1953125, 60466176]])

## Universal Funcs

In [ ]:
# Mathematical functions can be abstracted by using numpy, for example, if we need to know the sin of all elements in an array
# So we can use 
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [ ]:
np.sin(arr_2)

array([[-0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111]])